# constants.py
from enum import Enum

class State(Enum):
    SELECTING_CONFIG = 0 ,
    SELECTING_WALLET = 1,
    SELECTING_GROUP = 2,
    SELECTING_GROUP_OPTIONS = 3,
    SELECTING_BOT_TIME = 4,
    SETTING_LIMITS = 5,
    SETTING_BLACKLIST = 6,
    AWAITING_ETH_LIMIT = 7,
    AWAITING_BLACKLIST_ADD = 8,
    AWAITING_BLACKLIST_REMOVE = 9,
    AWAITING_INPUT_TIME_SLOT = 10